services:
  lrmu:
    build: .
    volumes:
      - ./logs:/tf/logs
      - ./plots:/tf/plots
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: ["gpu"]
