services:
  lrmu:
    build: .
    volumes:
      - ./logs:/tf/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
